CREATE TABLE [dbo].[Mail]
(
	[Id] INT NOT NULL  IDENTITY, 
    [From] NVARCHAR(254) NOT NULL, 
    [Subject] NVARCHAR(254) NULL, 
    [Body] NVARCHAR(MAX) NOT NULL, 
    [TimeStamp] DATETIMEOFFSET NOT NULL, 
    CONSTRAINT [PK_Mail] PRIMARY KEY (Id)
)
